-- CreateTable
CREATE TABLE "fomento" (
    "id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "countries" TEXT[],
    "region" TEXT[],
    "institution" TEXT NOT NULL,
    "program" TEXT NOT NULL,
    "call" TEXT NOT NULL,
    "supportType" TEXT NOT NULL,
    "organizations" TEXT[],
    "sector" TEXT[],
    "requiresPartner" BOOLEAN DEFAULT false,
    "partnerType" TEXT[],
    "TRLmin" TEXT,
    "TRLmax" TEXT,
    "technologies" TEXT[],
    "term" TEXT NOT NULL,
    "objective" TEXT NOT NULL,
    "elegibility" TEXT NOT NULL,
    "expenses" TEXT[],
    "minValueReembolsaveis" TEXT,
    "maxValueReembolsaveis" TEXT,
    "minValueSubvencao" TEXT,
    "maxValueSubvencao" TEXT,
    "supportTax" TEXT,
    "duration" TEXT,
    "tax" TEXT,
    "shortage" TEXT,
    "amortization" TEXT,
    "isESG" BOOLEAN DEFAULT false,
    "link" TEXT NOT NULL,
    "abgiInterest" BOOLEAN DEFAULT false,
    "status" TEXT NOT NULL,
    "lastRelease" TIMESTAMP(3),

    CONSTRAINT "fomento_pkey" PRIMARY KEY ("id")
);
